[options]

admin_passwd = admin

db_host = db
db_port = 5432
db_user = odoo_db_user
db_password = postgres

addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/custom
data_dir = /var/lib/odoo

C:\Users\Admin\projects\Equipment_Maintenance\custom